
ALTER TABLE [dbo].[ExamEnrolment]  WITH CHECK ADD  CONSTRAINT [FK776C8B3E3645DD75] FOREIGN KEY([Education])
REFERENCES [dbo].[Education] ([Id])
GO

ALTER TABLE [dbo].[ExamEnrolment] CHECK CONSTRAINT [FK776C8B3E3645DD75]
GO


